[package]
name = "theweatherchannel"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
weather_plugin = { path = "../../internal/weather_plugin" }
serde = "1.0"
serde_json = "1.0"
