[package]
name = "theweatherchannel"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
weather_plugin = { path = "../../crates/weather_plugin" }
serde = "1.0"
simd-json = "0.13"
serde_json = "1.0"
