[package]
name = "weather_structs"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }