class DummyFore:
    BLUE = ""
    GREEN = ""
    RED = ""
    LIGHTBLUE_EX = ""
    LIGHTGREEN_EX = ""
    LIGHTMAGENTA_EX = ""
    LIGHTYELLOW_EX = ""
    MAGENTA = ""
    YELLOW = ""
    RESET = ""
