[package]
name = "networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
networking_internal = { path = "../networking_internal" }
networking_macros = { path = "../networking_macros" }
