name: Update Website Data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install dependencies
        run: |
          cd dev-scripts
          cargo build
          cd ..
      - name: Update Executables
        run:
          ./dev-scripts/target/debug/dev-scripts update-docs "$GH_API_PAT"
        env:
          GH_API_PAT: ${{secrets.GH_API_PAT}}
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs bump"
          git push
